### ISSUE TITLE
java.lang.IllegalStateException: Failed to create configuration instance.

### ISSUE THREAD

**Issue by maurxce** [FairyProject/fairy#168]
```java
@FairyLaunch
public class Opdrachten extends Plugin {
    @Getter
    private static Opdrachten instance;

    @Override
    public void onPluginEnable() {
        instance = this;
        Log.info("Plugin Enabled.");
    }

}
```
```
[18:17:29 INFO]: [Opdrachten] Enabling Opdrachten v0.0.12
[18:17:30 INFO]: Version mappings loaded successfully!
[18:17:34 INFO]: [ERROR] Error while scanning classes for framework
[18:17:34 ERROR]: [Fairy] java.lang.IllegalStateException: Failed to create configuration instance.
[18:17:34 INFO]: Plugin Enabled.
```
How should I debug this?
There aren't any additional logs

**Comment by maurxce** [comment]
~~In addition to that, it seems like the following is not possible? (commented as well)~~
^ moved to https://github.com/FairyProject/fairy/issues/169

**Comment by LeeGodSRC** [comment]
Hey @maurxce , Thanks for reporting, can you show us a minimum reproducable project?

**Comment by maurxce** [comment]
Hey, thanks for your time and help
This issue was fixed as per your assumption:
> It's most likely caused by Configuration class having additional parameter
> which it's not supposed to have

My Configuration had a non-empty constructor, which expected an injected component as well.
Moving that to the method body worked out fine!
