### ISSUE TITLE
Custom item effects

### ISSUE THREAD

**Issue by terminalsin** [FairyProject/fairy#53]
Add custom attributes / listening capacity to items without causing a TPS leak:
- CustomObject extends ItemStack
- CustomObject listens to custom events (customobjectinteractevent, customobjectholderdamage event etc... only if it's in use-
- CustomObject initialized when deserialized 
- Stores all the necessary data in NBT

**Comment by terminalsin** [comment]
Exists in bukkit-items. Needs docs

**Comment by LeeGodSRC** [comment]
https://docs.fairyproject.io/modules/bukkit-item/
