### ISSUE TITLE
Improve menu api

### ISSUE THREAD

**Issue by terminalsin** [FairyProject/fairy#70]
Desired traits:

- [ ] Pass the menu reference in onClose and onOpen
- [ ] Improved handling. As of right now it is extremely chunky and can have issues with reopenings etc...

**Comment by LeeGodSRC** [comment]
Can you have some more detailed explaination about second one?

**Comment by terminalsin** [comment]
Sure, a bit of clarification as I was pressed. There are several conditions in which a GUI will be force closed, and those happen to be quite clonky and mess a lot with the menu api (eg: being in a nether portal, some other stuff etc…)

The proposed changes is to restrict the menu by default to only be closed by the user. Any other condition should be specified whilst building the menu.

**Comment by LeeGodSRC** [comment]
I wonder is there any reason why menu reference should be passed in onOpen and onClose while you are literally overridding the menu it self?

**Comment by LeeGodSRC** [comment]
https://docs.fairyproject.io/modules/bukkit-gui
