### ISSUE TITLE
BukkitTestingBase supports tear down for each test

### ISSUE THREAD

**Issue by lulu2002** [FairyProject/fairy#75]
Currently, we got BukkitTestingBase for init tests, but since it uses "@BeforeAll" for setting up, this means the data previous testing uses, might leaking to next one and cause testing fails.

It's good to have an option for reload plugins, making clean environment for testing.

![image](https://user-images.githubusercontent.com/41278925/163565480-f6d9deb9-17d0-4ab2-99d1-d25b64fbee32.png)

**Comment by LeeGodSRC** [comment]
Supported in Fairy 0.6
