### ISSUE TITLE
Module bukkit-xseries no longer compiles correctly since 0.6.4b2

### ISSUE THREAD

**Issue by terminalsin** [FairyProject/fairy#98]
### Pre 0.6.4b2
![firefox_nW2xCTJKgR](https://github.com/FairyProject/fairy/assets/30368557/db8cf1f8-82f6-4a40-9717-47f99f577820)

### Post 0.6.4b2
![javaw_7G2FiWlAyR](https://github.com/FairyProject/fairy/assets/30368557/eafca5ec-fee0-437f-bc01-e4f080e55954)

**Comment by LeeGodSRC** [comment]
Hey, this is intentional, relocate and shading is no longer a part of the fairy gradle plugin, you can use Gradle Shadow plugin to relocate it.
